### ISSUE TITLE
Unable to add filters when an store step is already in the trigger

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#103]
Select must appear before updates. But the UI does not allow to do this. Dragging pill on column header performs nothing.

Would be good to append a new filter after the last one of the same table.

Otherwise user is required to remove all store steps before changing the filter

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/103
- Originally Reported By: Brian Cardiff
- Originally Created At: 2014-03-13 17:54:20+00:00

**Comment by bcardiff** [comment]
UI now allows user to reorder steps. So it is no longer needed this logic.
Also loops were not available back then and those leads to no ultimate solution.
