### ISSUE TITLE
Counting string records after grouping does not work

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#107]
To reproduce:

- Create a table 'Users' with fields 'Name' and 'Sex'
- Store a couple of users: "name:Mark, sex: M", "name: Carol, sex: F"
- Create a 'Count' trigger that is going to send a message for each Sex, with the amount of users' names with this sex. 

Send a message that triggers this count.

An ElasticSearch error occurs:

```
#!json

Info: Executing trigger 'Count'
Error: 400 : {"error":"SearchPhaseExecutionException[Failed to execute phase [query_fetch], all shards failed; shardFailures {[_hRMPor1SR-VlWYAPCjCPg][mbuilder_application_82][0]: SearchParseException[[mbuilder_application_82][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\n \"facets\":{\n \"cbf6893f-958c-45f5-9055-d7e0f6decbc5_facet\":{\n \"terms_stats\":{\n \"key_field\":\"cbf6893f-958c-45f5-9055-d7e0f6decbc5\",\n \"value_field\":\"0efc7aa0-503e-4884-bc4e-0f9afa0c35a6\"\n }\n }\n }\n}]]]; nested: FacetPhaseExecutionException[Facet [cbf6893f-958c-45f5-9055-d7e0f6decbc5_facet]: value_field [0efc7aa0-503e-4884-bc4e-0f9afa0c35a6] isn't a number field, but a string]; }]","status":400}
```

This doesn't happen if you count a column with numeric values

Attached: Application that reproduces this problem

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/107
- Originally Reported By: Carolina Hadad
- Originally Created At: 2014-03-25 10:51:02+00:00

**Comment by bcardiff** [comment]
The issue is related to string aggregated column. Key can be string without issues as long as data column is an int.

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
