### ISSUE TITLE
'Foreach' pills are not replaceable

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#114]
Steps:
Add 'table 1'
Drag and drop table 1 to create a 'foreach' step.
Addd 'table 2'
Drag and drop table 2 to 'table 1' pill inside 'foreach' step.

Expected:
Foreach step now iterates table 2.

Actual:
nothing happens.

---
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/114
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-08-21 19:31:39+00:00

**Comment by pmallol** [comment]
Ok in version 1.2-pre1
