### ISSUE TITLE
Empy trigger list design

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#117]
We need an initial state design for this ![Screen Shot 2014-08-21 at 4.59.24 PM.png](https://bitbucket.org/repo/RxoABL/images/4259029359-Screen%20Shot%202014-08-21%20at%204.59.24%20PM.png)

---
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/117
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-08-21 20:06:57+00:00

**Comment by pmallol** [comment]
Ok in version 1.2-pre2
