### ISSUE TITLE
Style for import application upload

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#118]
![Screen Shot 2014-08-21 at 5.10.07 PM.png](https://bitbucket.org/repo/RxoABL/images/3128016174-Screen%20Shot%202014-08-21%20at%205.10.07%20PM.png)

---
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/118
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-08-21 20:11:21+00:00

**Comment by pmallol** [comment]
Ok in version 1.2-pre2
