### ISSUE TITLE
Style for boxes is missing

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#122]
Compare with: https://www.notableapp.com/posts/818297

![Screen Shot 2014-08-21 at 5.28.47 PM.png](https://bitbucket.org/repo/RxoABL/images/2122367729-Screen%20Shot%202014-08-21%20at%205.28.47%20PM.png)

---
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/122
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-08-21 20:29:45+00:00

**Comment by mmuller** [comment]
Ok in Version: 1.2-pre2
