### ISSUE TITLE
"Add a Resource Map collection" is not working

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#124]
Precon: have an account with Resmap collections and log in with that into mBuilder

Steps: Click on "Add a Resource Map collection", click on any of your collections.

Expected: A table appears with the fields of your collection.

Actual: nothing happens.

---
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/124
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-08-26 00:50:20+00:00

**Comment by mmuller** [comment]
This issue is still present in version 1.5.2.
Now an internal server error is logged in the browser's console.
