### ISSUE TITLE
When dragging Table headers, the "+" green ball is being shown on areas where you can't drop

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#153]
---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/153
- Originally Reported By: Brian Cardiff
- Originally Created At: 2014-09-05 21:36:57+00:00

**Comment by pmallol** [comment]
Still not fixed. Apparently there is no 'smooth' solution to this issue according to @nekron.
Making the green ball disappear could result in the "drop here" areas to stay visible.

**Comment by ggiraldez** [comment]
Should be fixed now. Also, the + icon is only show for drag operations over the actions area that will create a new action. For others, a link icon is used.

**Comment by mmuller** [comment]
Ok in Version: 1.2-pre2
