### ISSUE TITLE
Add style for column popup in triggers page

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#161]
![Screen Shot 2014-09-22 at 6.15.48 PM.png](https://bitbucket.org/repo/RxoABL/images/1355039346-Screen%20Shot%202014-09-22%20at%206.15.48%20PM.png)https://www.notableapp.com/posts/916996

---
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/161
- Originally Reported By: Carolina Hadad
- Originally Created At: 2014-09-22 21:16:16+00:00

**Comment by pmallol** [comment]
Ok in version 1.2-pre2
