### ISSUE TITLE
Add icon for deleting columns

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#166]
See this for design: https://www.notableapp.com/posts/916996

Functionality was there in previous version.

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/166
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-09-30 19:01:14+00:00

**Comment by pmallol** [comment]
Ok in version 1.2-pre1

**Comment by mmuller** [comment]
Ok in Version: 1.2-pre2
