### ISSUE TITLE
Show pills style when hovering over a row in tables

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#168]
Right now the row is being highlighted but texts in cells remains "unpilled". Show the pill border the same way we are doing with steps.

---
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/168
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-09-30 19:40:24+00:00

**Comment by pmallol** [comment]
Ok in version 1.2-pre1
