### ISSUE TITLE
"new step" in the bottom of steps lists should always add a step at the end of the list

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#169]
Right now it's doing that for all step types except when you have selected a 'for each'

---
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/169
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-09-30 19:49:06+00:00

**Comment by pmallol** [comment]
Ok in version 1.2-pre1
