### ISSUE TITLE
Add dropdown menu to "Add Step"

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#172]
---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/172
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-09-30 19:57:28+00:00

**Comment by pmallol** [comment]
Ok in version 1.2-pre1

**Comment by nditada** [comment]
@bcardiff This is not in release 1.4 right? Should we move it to 1.2?
