### ISSUE TITLE
When dragging a Table header, change style of "Foreach" pills to 'dropzone'

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#178]
---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/178
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-09-30 20:11:19+00:00

**Comment by pmallol** [comment]
Ok in version 1.2-pre1

**Comment by pmallol** [comment]
Unbound pills in Foreach step do not change style to drop zone.

**Comment by mmuller** [comment]
Ok in Version: 1.2-pre2
