### ISSUE TITLE
Pills are not stored in outgoing messages

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#179]
This only happens in STG, it's probably something related to the new pill component.

Create a trigger that stores something in a table ( a pill obtained from the incoming message for example). Then send an email using this pill we just stored.

Save the trigger.
Open the trigger again.

Obtained: the pill was not stored in the outgoing message. It disapeared

---
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/179
- Originally Reported By: Carolina Hadad
- Originally Created At: 2014-10-01 23:48:27+00:00

**Comment by pmallol** [comment]
Ok in version 1.2-pre1
