### ISSUE TITLE
After deleting a column from a table the "Recent Activity" page throws Server Error

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#191]
* Found in version 1.1-63-g6224c7d
* 
* There is a Trigger created that store values in a table
* Go to the Trigger 
* Delete a column
* Go to the Recent Activity
* 
* Obtained: Server error is thrown

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/191
- Originally Reported By: Mauricio Müller
- Originally Created At: 2014-10-15 15:40:10+00:00

**Comment by asterite** [comment]
Also happens if a table is deleted

**Comment by asterite** [comment]
Also happens if a table is deleted

**Comment by mmuller** [comment]
Ok in v1.2-pre2
