### ISSUE TITLE
Recent Activity cannot be sorted by Trigger name and an internal server error is thrown

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#192]
Found in version 1.1-63-g6224c7d

Navigate to Recent Activity
Click 'Trigger' from the table header

Obtained: 
The list is not sorted by Trigger name.
Internal server error is logged in the browser console 

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/192
- Originally Reported By: Mauricio Müller
- Originally Created At: 2014-10-15 16:59:32+00:00

**Comment by mmuller** [comment]
Ok in Version: 1.4-pre3
