### ISSUE TITLE
Expose available external trigger with parameters through API

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#194]
Provide a discovery endpoint so we can query externally the list of external triggers with their parameters.

---
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/194
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-10-21 20:20:16+00:00

**Comment by pmallol** [comment]
Ok in version 1.2-pre1
