### ISSUE TITLE
Add oauth token authentication option to external triggers

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#195]
In the external triggers show to option buttons:

"( ) Basic auth: Use this if a 3rd party application will be calling this trigger and you can specify user and password"
"( ) Oauth token: Use this if you are going to call this trigger from another InSTEDD application."

---
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/195
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-10-21 20:29:37+00:00

**Comment by mmuller** [comment]
Ok in Version: 1.2-pre2
