### ISSUE TITLE
Can't remove parameter in External Trigger

### ISSUE THREAD

**Issue by edjez** [instedd/mbuilder#203]
Can add external parameters by typing in a name but can't delete

**Comment by nditada** [comment]
closed it by mistake

**Comment by nditada** [comment]
Add a 'delete' button for each parameter. @jkicillof did we have a design for this?

**Comment by jkicillof** [comment]
I think we should remove redundant elements first. There's no need for a CRUD list and a preview of the url and having both elements  draggable pills. Also, it's a bit confusing having the parameter's name and parameter's value the same name. When a user adds a parameter, it's shown directly on the url like "new_parameter=new_parameter_value", on click becomes editable.
![application_externaltriggers_editor](https://cloud.githubusercontent.com/assets/5031636/7483823/bd55966a-f358-11e4-84ec-3b4e1cd82c65.png)

**Comment by nditada** [comment]
:+1: Perfect.

**Comment by bcardiff** [comment]
The "copy link" might not be that useful. Usually user will need to add some sort of authentication and replace argument values. I will vote for a "help" or "how to" that will explain how to invoke the action directly or from other InSTEDD apps via hub.

Also, notice that the external trigger name is missing in the url.

**Comment by jkicillof** [comment]
Copy link replaced and url fixed.
![application_externaltriggers_editor](https://cloud.githubusercontent.com/assets/5031636/7493522/06f783f8-f3d8-11e4-913a-455cc676f134.png)

**Comment by juanboca** [comment]
Will this also be applied to the step definition of the trigger? Or should I create a new issue?
Right now if you make a mistake when dropping a pill the only way to go back is by deleting the step.
![screen shot 2015-05-06 at 11 10 49 am](https://cloud.githubusercontent.com/assets/488553/7494896/e62e4f72-f3e0-11e4-8622-6700dd390df3.png)

**Comment by bcardiff** [comment]
@juanboca I don't think so. There is style still pending to be applied to that box thou. But the @jkicillof proposal would not apply directly to add/remove hub's open struct fields.

**Comment by bcardiff** [comment]
Empty help page created at https://github.com/instedd/mbuilder/wiki/invoke_external_triggers

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
