### ISSUE TITLE
External Trigger using incoming Date Causes Trigger to Fail w undefinedMethod f NilClass

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#219]
Originally reported by @edjez in BitBucket

Repro: An external trigger functions fine Try to store the date ({yyyymmdd} pill) of the incoming trigger in a table
Trigger fails and activity list shows:
Info: Executing trigger 'Nudge24' Error: undefined method `[]' for nil:NilClass

**Comment by pmallol** [comment]
Ok in version 1.2-pre1
