### ISSUE TITLE
Update/create Resourcemap facility from Mbuilder is not working

### ISSUE THREAD

**Issue by mmuller** [instedd/mbuilder#220]
Found in Version: 1.1.1

**Comment by nditada** [comment]
Does the current Resmap hub connector support R/W? See #245

**Comment by nditada** [comment]
This issue is pre-hub, we might be able to just close it.

**Comment by bcardiff** [comment]
mbuilder-resmap does not go through hub. Yet i would expect to be fixed already this issues.



—

**Comment by mmuller** [comment]
Tested in version 1.2-pre2

Create Facilities is working.
Facilities cannot be updated from mBuilder.
Only the GET request is sent to Resourcemap (POST is not sent).

suggestion by @bcardiff:

https://github.com/instedd/mbuilder/blob/1.2-pre2/app/models/tables/resource_map.rb#L48 should call to https://github.com/instedd/mbuilder/blob/1.2-pre2/app/models/database_execution_context.rb#L74

**Comment by pmallol** [comment]
Ok in version 1.2-pre3
