### ISSUE TITLE
External trigger is saved even though there is an empty parameter

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#224]
Found in version 1.1-87-g272c453

Preconditions:
User is signed in and already has an application "X".

1. Navigate to the application "X"
2. Select the 'Triggers' tab
3. Click the 'Add trigger' button and select 'External trigger'
4. Click 'Add additional parameter' 
5. Click the 'Save' button

Obtained: the trigger is saved with an empty parameter

Expected: a notice should appear indicating the parameter is empty and the user should not be able to save changes after the required fields are changed.

**Comment by nditada** [comment]
related to #203

**Comment by bcardiff** [comment]
Also, the duplicate parameters names are not supported. So a validation for those where added too.

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
