### ISSUE TITLE
'Add step' button overlays the operators popup 

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#237]
Found in version 1.1.1-4

Precondition: user has an application "X" with a message trigger "Y"

1. Open application "X"
2. Select Trigger's tab and open trigger "Y"
3. In the message container write any word and highlight it 
4. Drag and drop the highlighted word in the 'drop here' area (a condition appears: "if foo **equal** [empty]")
5. Click on "equal"

Obtained: the operators popup gets covered by the 'new-action' div that contains the 'Add step' button.

NOTE: the same occurs when a column's title is dragged and dropped in the 'drop here' area with the condition "if **all of** foo **equal** [empty]", both operators popups get covered. 

![screen shot 2015-01-08 at 11 32 12 am](https://cloud.githubusercontent.com/assets/9214460/5664300/2d326940-972e-11e4-8279-b66d251a48a2.png)

**Comment by chadad** [comment]
In version 6cdbae6721 the popup does not overlap the 'Add step' button but the actions above 'are greater than' are not clickable.

**Comment by pmallol** [comment]
Found in version g6cdbae6

The operators popup still gets caught under the 'Add step' button and same happens when adding another step, resulting in the button of the middle overlaying the dropdown menu.

![screen shot 2015-01-15 at 5 25 56 pm](https://cloud.githubusercontent.com/assets/9214460/5765932/5f8ef918-9cdc-11e4-9ab6-85eb053f0b16.png)
![screen shot 2015-01-15 at 5 27 00 pm](https://cloud.githubusercontent.com/assets/9214460/5765973/9a7731bc-9cdc-11e4-92ec-83b6bfa5e82b.png)

**Comment by pmallol** [comment]
Ok in version 1.2-pre1
