### ISSUE TITLE
Expose numbers with 0 as decimal without decimals so that it can be used as phone number

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#241]
Found in v.1.1.2

Preconditions:
User has: 
a) a project and call flow in Verboice already set up with a Callcentric channel
b) an app in mBuilder with an external trigger with a variable 'phone_number' and a dummy table that storages the variable.
c) Verboice and mbuilder connectors set up in Hub and a task that links the variable 'address' from the 'finished call' from Verboice as the event, with the variable 'phone_number' in the trigger action from mBuilder.

1. Call Verboice's project
2. Open the tab 'Recent Activity' in mBuilder's app

Obtained: the phone number is stored in mBuilder with decimals (.0)
![screen shot 2015-01-16 at 11 22 37 am](https://cloud.githubusercontent.com/assets/9214460/5777523/01ed7d5c-9d72-11e4-8259-0bf1069ad1b3.png)
 
Expected: the number should be stored without any decimals when the decimal is 0 so that it can be used as a phone number (i.e.: instead of '17772433041.0', display '17772433041')

NOTE: same happens when storing the date pill (yyyymmdd).
![screen shot 2015-02-02 at 2 42 45 pm](https://cloud.githubusercontent.com/assets/9214460/6005521/cc7e9310-aae9-11e4-96ca-2313391044c5.png)

**Comment by bcardiff** [comment]
It seems the user story of storing additional data per phone in mbuilder works fine. The phone numbers are stored as decimals, but the lookup works fine with or without decimals.

When a decimal number is going out form mbuilder (hub action / hub data) it was sent in a user friendly manner (without decimal). So the user story should be supported.

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
