### ISSUE TITLE
No space between buttons in "empty list" view of trigger list.

### ISSUE THREAD

**Issue by nditada** [instedd/mbuilder#242]
![screen shot 2015-01-19 at 3 20 18 pm](https://cloud.githubusercontent.com/assets/1359189/5805571/c0aca172-9fee-11e4-855d-04eeb9fb29e6.png)

**Comment by nditada** [comment]
Also, reword as "You have no triggers yet.", in a single line, then "Add a trigger." In the second line.

**Comment by pmallol** [comment]
Ok in Version: 1.2-pre1
