### ISSUE TITLE
UI issues in Trigger edition

### ISSUE THREAD

**Issue by nditada** [instedd/mbuilder#243]
It's really confusing where to type the name and what "New Trigger" and "Trigger name" are. @jkicillof How was the design for this? 

![screen shot 2015-01-23 at 3 26 20 pm](https://cloud.githubusercontent.com/assets/1359189/5880126/7a2e34bc-a314-11e4-8b3b-1d7d48aaae94.png)

**Comment by jkicillof** [comment]
You shouldn't be seeing the project's tab along with the new trigger form. You should be seeing something like [this] (https://www.notableapp.com/posts/922614) with "New Trigeer" as title.

**Comment by nditada** [comment]
Ok, so we have to:
- [ ] Hide the tabs inside the edition of triggers
- [ ] Add a note below the "Edit Trigger" Title that reads: "Define the behaviour of the trigger by typing an example of a message and indicating the actions that you want to take"
- [ ] Add space between "Edit Trigger" and the "Trigger name"
- [ ] Apply correct styles to titles and subtitles

**Comment by mmuller** [comment]
Ok in version: 1.2-pre4
