### ISSUE TITLE
Error in trigger that attempts to use phonebook

### ISSUE THREAD

**Issue by nditada** [instedd/mbuilder#244]
Not sure if this is the minimal reproduction, I had:
 - A flow in verboice that stored a number in the phonebook 
 - A trigger in mbuilder that queried that number including the phonebook as an entityset
 
- Calling the trigger resulted in:
'
Error: unexpected character at line 1, column 1 [parse.c:637]
'
![screen shot 2015-01-23 at 3 38 39 pm](https://cloud.githubusercontent.com/assets/1359189/5880294/009e8686-a316-11e4-9201-53953ef9120e.png)

**Comment by nditada** [comment]
Writing produces the same result

**Comment by nditada** [comment]
Diagnostic: Verboice-connector is failing when the result of the query on a phonebook instead of returning an empty result: http://poirot-stg.instedd.org/activities/00891e49-edd4-0d73-af90-0ca43540fa85

**Comment by ggiraldez** [comment]
Fixed in Hub's commit https://github.com/instedd/hub/commit/b1f487cab45d2b6277cea28e60720bfdad5edc89

**Comment by pmallol** [comment]
Works ok in version 1.2-pre2
