### ISSUE TITLE
Add time zone to time picker in Periodic Tasks

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#251]
Found in Version 1.2-pre1

Adding the time zone (e.g: UTC) next to the time picker would allow no doubt about the time the trigger will run.

![screen shot 2015-01-30 at 11 15 48 am](https://cloud.githubusercontent.com/assets/9214460/5976885/6644fa46-a871-11e4-8c79-73b048e9ba5c.png)

**Comment by edjez** [comment]
Suggest a timezone for the whole project. 
It also affects the YYMMDD pill (the date has to be in the local timezone not UTC)

**Comment by nditada** [comment]
Only show the reference of the project timezone, let's not add overrides for now.

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
