### ISSUE TITLE
Unable to replace the pill of the Foreach step 

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#253]
Found in version 1.2-pre1

1. Add a message trigger
2. Add a Loop step
3. Add new data 
4. Add a Field
5. Drag and drop the Field on top of the '???' pill of the Foreach step

Obtained: the '???' pill is highlighted but not replaced

Expected: the pill of the Foreach step is replaced.

**Comment by romeroadrian** [comment]
Loop steps only accept tables as parameters (not columns or particular fields). Will fix the UI to reflect this (unbounded pill at foreach step will only highlight when dragging a table reference).

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
