### ISSUE TITLE
Validation popup appears in the top left corner

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#257]
Found in version 1.2-pre1

1. Add a message trigger
2. Add New Data and a Field
3. Right click on 'Field 1'

Obtained: the validation popup shows up in the top left corner of the web app.

Expected: the popup appears right under 'Field 1'
 
![screen shot 2015-02-03 at 12 52 22 pm](https://cloud.githubusercontent.com/assets/9214460/6024801/8fa955ec-abac-11e4-8e07-b97af9e1c6cd.png)

**Comment by bcardiff** [comment]
Seems to be fixed already in 1.4. Confirmed it is present in 1.2.1.

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
