### ISSUE TITLE
App Import/Export Does not port External Triggers

### ISSUE THREAD

**Issue by edjez** [instedd/mbuilder#259]
When exporting an mbuilder app with external triggers, when importing they don't appear. Not sure if schedule triggers also have the same issue

**Comment by pmallol** [comment]
@edjez, periodic triggers are imported just fine. This bug is fixed in version STG 1.2-pre1

**Comment by edjez** [comment]
Ah... "are" --> "will be" :)
Production at http://mbuilder.instedd.org/ <http://mbuilder.instedd.org/> is currently 1.1.2 
Thanks looking forward to it!

**Comment by pmallol** [comment]
Yes! sorry, that's what I meant :)

**Comment by mmuller** [comment]
Ok in Version: 1.2-pre2
