### ISSUE TITLE
Support external steps

### ISSUE THREAD

**Issue by nditada** [instedd/mbuilder#261]
Using the manifests from Verboice, maybe supporting json instead of xml.
- [x] Add a tab "external services" inside applications 
- [x] Show the same list for registering external services in verboice
- [x] Use JSON instead of XML
- [x] Provide and link an example in that window
- [x] Input variables are shown as placeholders with the "Display name" as the label, users can drag pils to the right of the input variable
- [x] Response variables are shown at the bottom of the step and can be dragged and dropped like any other pill
- [x] Support only response types "variable" and "none" for now.
- [x] Add the new step type as an element in the dropdown list that appears when clicking on "Add step", show the icon there.
- [x] Support this step in import/export of apps

**Comment by bcardiff** [comment]
Should we support external steps in hub, and expose them in mbuilder as action.
This could be done behind scenes in mbuilder, but will allow to move external services manifest support from verboice to all instedd apps potentially.

**Comment by nditada** [comment]
@bcardiff Great idea, but let's do it after we implement it in mBuilder, so we plan the design for the integration into hub with both use cases in mind. If we want to do it seamlessly, the external step connector in hub would have to expose apis to upload manifests, etc.

**Comment by nditada** [comment]
@Mscebba Can you help building this new tab?
