### ISSUE TITLE
Spelling on trigger editor

### ISSUE THREAD

**Issue by steesdale** [instedd/mbuilder#263]
When designing a trigger  ->  Use tables to store o retrieve data... Should be " OR retrieve data"  

![screen shot 2015-02-06 at 9 15 08 am](https://cloud.githubusercontent.com/assets/3987608/6080930/6d41e8be-ade3-11e4-99d7-6c5a7af0d0fa.png)

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
