### ISSUE TITLE
Table inside 'Data' has no top margin

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#265]
Found in version 1.2-pre1

1. Navigate to Data 
2. Create new from CSV
3. Complete name and click 'Import'

Obtained: there is no space between the buttons located next to the table's name and the table.

![screen shot 2015-02-09 at 11 33 17 am](https://cloud.githubusercontent.com/assets/9214460/6108236/206c0de8-b050-11e4-8de4-5921b8cf1c98.png)

**Comment by mmuller** [comment]
Ok in version 1.4-pre2
