### ISSUE TITLE
White rectangle appears when user has no Resourcemap collections

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#267]
Found in version 1.2-pre1

Preconditions:
The user does not have any Resource Map collections.

1. Add a trigger
2. Add a Resource Map collection

Obtained: a small white rectangle appears.

Expected: the action should be disabled.

![screen shot 2015-02-09 at 12 27 44 pm](https://cloud.githubusercontent.com/assets/9214460/6109081/1841b8a0-b057-11e4-9808-65ad273506c4.png)

**Comment by mmuller** [comment]
Ok in version 1.4-pre3
