### ISSUE TITLE
Number of records to import is between parenthesis

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#273]
![screen shot 2015-02-09 at 1 53 57 pm](https://cloud.githubusercontent.com/assets/9214460/6114628/313c85e8-b07e-11e4-97fa-05f7e6189f6d.png)

**Comment by ggiraldez** [comment]
Fixed in 8768baf09494ab69e8a0c1752ef07c7262c979f7

**Comment by pmallol** [comment]
Ok in version 1.2-pre2
