### ISSUE TITLE
Icons for 'Condition' and 'Hub Action' steps are missing

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#280]
Found in version 1.2-pre2

1. Open an application
2. Add a message trigger

![screen shot 2015-02-27 at 3 32 46 pm](https://cloud.githubusercontent.com/assets/9214460/6418720/24de0d1e-be96-11e4-9f77-3ea82c8fcd53.png)

**Comment by bcardiff** [comment]
They are not missing. The condition icon is "<?>". But the hub action icon should be the appropriate.
#306 created to track this.
