### ISSUE TITLE
Error in console when adding a Verboice's call flow as data

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#285]
Found in mbuilder v.1.2-pre2
(Verboice 2.5-pre4)

Preconditions:
User has a project and call flow in Verboice

1. Create an application 
2. Add a message trigger
3. 'Add data from Hub'
4. Select Verboice connector > Projects > 'X project' > 'X Call flow'

Obtained: no data is added and an error appears in console

Expected: the option to add data from a call flow should be disabled and only phone books should be able to add as data from Verboice. 

![screen shot 2015-03-03 at 10 07 43 am](https://cloud.githubusercontent.com/assets/9214460/6463789/3bfcc5d4-c194-11e4-879c-b05e8faa6a38.png)

**Comment by vtiffenberg** [comment]
This happens with every entity set which is not designed as a collection to query. Entity sets like Phone Book which are supposed to be used as tables can be selected with no problem, others like Call Flows, or Applications (anything on the project structure) have no entity_definition and fail with that same error. Hub's picker is making no distinction in between them at the time. Will add this to Hub. But it't not pertinent to mBuilder's release

**Comment by nditada** [comment]
Thanks! can you reference the ticket in Hub here and close this one?

**Comment by mmuller** [comment]
Ok in version 1.2-pre3
