### ISSUE TITLE
Table's columns cannot be used as message recipient

### ISSUE THREAD

**Issue by mmuller** [instedd/mbuilder#289]
Found in version:  1.2-pre3

Preconditions: 
There is a Trigger.
There is a table with one field. This column contains one record.

Steps:
Press 'Add step'
Choose 'Send SMS' from the options
Fill the message body
Click and drag the column header and drop it into the field 'to' of the message (it would be the message recipient)
The column is not dropped into the field 'to'
Press 'Save'

Obtained:
An error message is thrown (see the screenshot)
The Trigger cannot be saved

Expected:
The column header can be dropped into the field 'to' of the Message

Log info:

Started PUT "/applications/190/external_triggers/91" for 190.245.237.31 at 2015-04-15 12:34:00 +0000
Processing by ExternalTriggersController#update as JSON
  Parameters: {"name"=>"test", "tables"=>[{"name"=>"Recipients", "guid"=>"8604c7b4-c6f3-4801-a37b-b2e27305a86b", "kind"=>"local", "fields"=>[{"name"=>"Phone Number", "guid"=>"cdaa3341-8989-40a6-a2ed-97e3f3f6d051", "valid_values"=>"", "$$hashKey"=>"00Q", "editmode"=>false}], "protocol"=>["query", "update", "insert"], "$$hashKey"=>"00M", "editmode"=>false}], "parameters"=>[{"kind"=>"parameter", "guid"=>"9630ac84-4cc3-4883-b3dc-944aad0204d0", "name"=>"assay_name", "$$hashKey"=>"00F"}], "actions"=>[{"kind"=>"create_entity", "table"=>"8604c7b4-c6f3-4801-a37b-b2e27305a86b", "field"=>"cdaa3341-8989-40a6-a2ed-97e3f3f6d051", "pill"=>{"kind"=>"literal", "guid"=>"176fbecc-b351-4e6f-9c26-8b5532442dbe", "text"=>"+541101234567", "$$hashKey"=>"02B", "editmode"=>false}, "$$hashKey"=>"00I"}, {"kind"=>"send_message", "message"=>[{"kind"=>"text", "guid"=>"assay_name: "}, {"kind"=>"parameter", "guid"=>"9630ac84-4cc3-4883-b3dc-944aad0204d0", "name"=>"assay_name"}], "recipient"=>{"kind"=>"field_ref", "guid"=>"cdaa3341-8989-40a6-a2ed-97e3f3f6d051", "$$hashKey"=>"033"}, "$$hashKey"=>"00K", "recipientEditable"=>"false"}], "auth_method"=>"oauth", "application_id"=>"190", "id"=>"91", "external_trigger"=>{"actions"=>[{"kind"=>"create_entity", "table"=>"8604c7b4-c6f3-4801-a37b-b2e27305a86b", "field"=>"cdaa3341-8989-40a6-a2ed-97e3f3f6d051", "pill"=>{"kind"=>"literal", "guid"=>"176fbecc-b351-4e6f-9c26-8b5532442dbe", "text"=>"+541101234567", "$$hashKey"=>"02B", "editmode"=>false}, "$$hashKey"=>"00I"}, {"kind"=>"send_message", "message"=>[{"kind"=>"text", "guid"=>"assay_name: "}, {"kind"=>"parameter", "guid"=>"9630ac84-4cc3-4883-b3dc-944aad0204d0", "name"=>"assay_name"}], "recipient"=>{"kind"=>"field_ref", "guid"=>"cdaa3341-8989-40a6-a2ed-97e3f3f6d051", "$$hashKey"=>"033"}, "$$hashKey"=>"00K", "recipientEditable"=>"false"}], "name"=>"test", "parameters"=>[{"kind"=>"parameter", "guid"=>"9630ac84-4cc3-4883-b3dc-944aad0204d0", "name"=>"assay_name", "$$hashKey"=>"00F"}], "auth_method"=>"oauth"}}
Completed 500 Internal Server Error in 1731.9ms

RuntimeError (Unknown pill for 'field_ref' kind):
  app/models/hasheable.rb:18:in `block in from_hash'
  app/models/suitable_class_finder.rb:79:in `call'
  app/models/suitable_class_finder.rb:79:in `value'
  app/models/suitable_class_finder.rb:69:in `find_in'
  app/models/suitable_class_finder.rb:53:in `find_leaf_subclass_of'
  app/models/hasheable.rb:16:in `from_hash'
  app/models/actions/send_message.rb:47:in `from_hash'
  app/models/hasheable.rb:17:in `block in from_hash'
  app/models/suitable_class_finder.rb:76:in `call'
  app/models/suitable_class_finder.rb:76:in `value'
  app/models/suitable_class_finder.rb:69:in `find_in'
  app/models/suitable_class_finder.rb:53:in `find_leaf_subclass_of'
  app/models/hasheable.rb:16:in `from_hash'
  app/models/hasheable.rb:10:in `block in from_list'
  app/models/hasheable.rb:9:in `map'
  app/models/hasheable.rb:9:in `from_list'
  app/controllers/external_triggers_controller.rb:78:in `set_external_trigger_data'
  app/controllers/external_triggers_controller.rb:33:in `update'

![screen shot 2015-04-15 at 9 32 06 am](https://cloud.githubusercontent.com/assets/518152/7158696/f4f56c00-e352-11e4-8728-d1b4c1240ddc.png)

**Comment by nditada** [comment]
Resolve this as a 1.2.1 Hotfix, it affecting 1.2 in production.

**Comment by mmuller** [comment]
Ok in version 1.2.1-pre1
