### ISSUE TITLE
Error when executing a trigger with a hub action step that triggers an external trigger 

### ISSUE THREAD

**Issue by pmallol** [instedd/mbuilder#291]
Found in 1.2 Prod

Precondition:
There is an external trigger 'Foo' created

1. Create a message trigger 'Bar' with a message "hub"
2. Add a Hub Action step that triggers the external trigger 'Foo'
3. Test triggering 'Bar' in the sandbox adding a number and the message "hub"

Obtained: ```Error: unexpected character at line 1, column 1 [parse.c:637]```

Poirot log: http://poirot.instedd.org/activities/37a48ae6-3ab5-b9a8-2a75-6fe8e90a68a2

**Comment by bcardiff** [comment]
this is fixed in hub hotfix-1.0.2 it does not needs any mbuilder change

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
