### ISSUE TITLE
Fusion Tables data cannot be retrieved

### ISSUE THREAD

**Issue by mmuller** [instedd/mbuilder#292]
mBuilder version: 1.2
Hub version: development

Preconditions:
Given a Message Trigger that contain a table from Fusion Table (added via Hub)

Steps:
Add a message
Include a field from the table in the message
Test the trigger using the sandbox

Obtained:
The following error message is thrown "Error: unexpected character at line 1, column 1 [parse.c:637]"

![screen shot 2015-04-28 at 9 06 51 am](https://cloud.githubusercontent.com/assets/518152/7369233/b3f76c10-ed86-11e4-9d09-9c87f592e7ee.png)

**Comment by bcardiff** [comment]
this is fixed in hub hotfix-1.0.2 it does not needs any mbuilder change

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
