### ISSUE TITLE
Only Question ID can be retrieved from Pollit

### ISSUE THREAD

**Issue by mmuller** [instedd/mbuilder#293]
mBuilder version: 1.2
Hub version: development

Preconditions:
Given a Message Trigger that contain a table from Pollit (added via Hub)
The table contains the Question properties

Steps:
Add a message trigger. It will receive the Question 'Title'
Add a message in order to send the Question properties (desc, id, etc)
Test the trigger using the sandbox

Obtained:
Only the Question 'ID' is sent.

Expected:
The Question properties (desc, id, etc) are sent

**Comment by mmuller** [comment]
![screen shot 2015-04-28 at 9 48 20 am](https://cloud.githubusercontent.com/assets/518152/7369860/c3a93ae4-ed8b-11e4-9683-015109bc3df1.png)
![Uploading Screen Shot 2015-04-28 at 9.48.07 AM.png . . .]()

**Comment by bcardiff** [comment]
This seems to be no longer the case from version 1.2.1
