### ISSUE TITLE
Periodic Task time is wrongly preserved across submissions 

### ISSUE THREAD

**Issue by bcardiff** [instedd/mbuilder#296]
mbuilder version: 1.3-pre1

Steps:
Create and App with GMT-3 default timezone
Create a periodic trigger with time 10:00:00
Save the periodic trigger
Open periodic trigger for edition.

Obtained
Periodic trigger time is displayed as 13:00:00

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
