### ISSUE TITLE
Can't remove pill on the step definition of an External Trigger

### ISSUE THREAD

**Issue by juanboca** [instedd/mbuilder#297]
On a step definition from an external trigger:
Right now if you make a mistake when dropping a pill the only way to go back is by deleting the step.

![screen shot 2015-05-06 at 11 10 49 am](https://cloud.githubusercontent.com/assets/488553/7591021/c15757c8-f8a1-11e4-9396-eae6d4a8bbf1.png)

**Comment by nditada** [comment]
Solution will be to add an 'x' on hover over pills, to remove binding and return it to empty state.

**Comment by pmallol** [comment]
Ok in version 1.4-pre2
