### ISSUE TITLE
Empty drop down menu if no external service is defined

### ISSUE THREAD

**Issue by bcardiff** [instedd/mbuilder#299]
version: 1.3-pre1

![screen shot 2015-05-15 at 2 57 12 pm](https://cloud.githubusercontent.com/assets/459923/7658719/d1a9057c-fb12-11e4-8966-3c988482103d.png)

**Comment by bcardiff** [comment]
fixed together with #300

**Comment by mmuller** [comment]
Ok in version: 1.4-pre3
