### ISSUE TITLE
Missing style on external service drop down

### ISSUE THREAD

**Issue by bcardiff** [instedd/mbuilder#300]
version: 1.3-pre1

![screen shot 2015-05-15 at 3 19 21 pm](https://cloud.githubusercontent.com/assets/459923/7659089/eca6b858-fb15-11e4-9be6-ec26535d730e.png)

**Comment by bcardiff** [comment]
current beahaviour:
![screen shot 2015-08-12 at 2 18 30 pm](https://cloud.githubusercontent.com/assets/459923/9231342/269f8a34-40fe-11e5-859e-d81a7888dbcf.png)
![screen shot 2015-08-12 at 2 18 39 pm](https://cloud.githubusercontent.com/assets/459923/9231344/28fb7edc-40fe-11e5-9eeb-9f3ee19ab1e3.png)

**Comment by mmuller** [comment]
Ok in Version: 1.4-pre3
