### ISSUE TITLE
Update icons for hub actions and external services

### ISSUE THREAD

**Issue by bcardiff** [instedd/mbuilder#306]
@Mscebba we need 25x25 and 40x40 icons for the hub actions as in 

![screen shot 2015-07-28 at 2 39 31 pm](https://cloud.githubusercontent.com/assets/459923/8938698/82425390-3536-11e5-8a99-343d4968c806.png)

And we need a 25x25 cloud for external services.

Please, update icons-25x25.png, icons-40x40.png and application.scss classes `.i25-extdata`  , `.i25-hub` , `.i40-hub` in master.

**Comment by mmuller** [comment]
Ok in version 1.4-pre2

**Comment by mmuller** [comment]
Ok in version: 1.4-pre3
