### ISSUE TITLE
Support aggregate functions when using pills in steps other than message

### ISSUE THREAD

**Issue by nditada** [instedd/mbuilder#311]
Currently aggregate functions only work inside the message step.

**Comment by nditada** [comment]
@nditada please provide a use case

**Comment by asterite** [comment]
The use case is in `if` condition and basically any place where you can drop a "field value" pill.

**Comment by bcardiff** [comment]
@asterite will a user be able to insert the aggregation of a value in a table?
I bet it is a corner case in how the pills are rendered in the tables. Although I don't have a real use case for this story.

**Comment by asterite** [comment]
Doesn't seem to work, I'll try to fix it

**Comment by asterite** [comment]
After a long time I understood how everything works and was able to implement it :-)

**Comment by mmuller** [comment]
Ok in version 1.6-pre4
