### ISSUE TITLE
Style is lost in aggregate functions while typing in send message

### ISSUE THREAD

**Issue by bcardiff** [instedd/mbuilder#312]
Drop a pill. Select an aggregate function.
It appears as
![screen shot 2015-08-12 at 12 37 39 pm](https://cloud.githubusercontent.com/assets/459923/9228467/04d9397c-40ef-11e5-84c5-32a7fbdd0ce5.png)

start typing and the style is left as
![screen shot 2015-08-12 at 12 37 54 pm](https://cloud.githubusercontent.com/assets/459923/9228478/08c6de9a-40ef-11e5-8c24-0307d8b23d4e.png)

**Comment by mmuller** [comment]
Ok in Version: 1.4-pre3
