### ISSUE TITLE
Create an external service using symbols instead of a valid URL causes server error

### ISSUE THREAD

**Issue by mmuller** [instedd/mbuilder#313]
Found in version:
1.4-pre3

Steps:
Go to create an External Service
Fill the 'URL' field with '#@$%^' 
Press 'Save'

Obtained:
Create an external service using symbols instead of a valid URL causes server error

Expected:
An error message should be shown

**Comment by nditada** [comment]
@mmuller This is not a critical bug as it's not blocking any functionality. It's only validation what's missing. The server is still functional after the error ritght?

**Comment by mmuller** [comment]
@nditada Minor severity refers to minor user interface details. Since this action sends crashes the application the issue severity is critical, but you're right the server is still functional.

**Comment by bcardiff** [comment]
it was a minor fix. implemented for 1.5
