### ISSUE TITLE
Change inline expandable pills in triggers list for a list container

### ISSUE THREAD

**Issue by nditada** [instedd/mbuilder#318]
Add 3 separate boxes (one for each type of trigger). Add the 'new' button for each type in the context of the corresponding box.

**Comment by bcardiff** [comment]
@Mscebba we would need to change https://github.com/instedd/mbuilder/tree/master/app/assets/images/instedd-bootstrap/icons/72/grey images to match https://github.com/instedd/instedd-bootstrap/blob/master/app/assets/images/instedd-bootstrap/icons/72/grey/folder.png
