### ISSUE TITLE
Show 'drop' style hint on column headers for discoverability

### ISSUE THREAD

**Issue by nditada** [instedd/mbuilder#330]
There's no indication right now that a pill can be dropped to a column header for filtering. I believe we had a design where a "filter" hint (similar to the 'store' one) would appear when hovering on the table or column header. @jkicillof ?

**Comment by bcardiff** [comment]
detailed in https://github.com/instedd/mbuilder/issues/325#issuecomment-137537392 a filter text will appear on hover

**Comment by asterite** [comment]
It now looks like this:

![screenshot 2016-07-11 14 42 30](https://cloud.githubusercontent.com/assets/209371/16740519/bbd47ee2-4775-11e6-92c4-5cc4dd617735.png)

So at least now there's an indication, but the final style should be decided in #325

**Comment by mmuller** [comment]
Ok in version 1.6-pre4
