### ISSUE TITLE
Phone numbers stored as float fail later when sending SMS

### ISSUE THREAD

**Issue by nditada** [instedd/mbuilder#331]
If sender phone numbers are stored in a table, mBuilders stores them as float. Using those numbers later to send SMS results in a Nuntium error when trying to send to a number like 12323234.0.

Steps to reproduce:
create a trigger that subscribes a caller. drag and drop the sender phone number to a new empty table.
create a periodic trigger that sends SMS to subscribers in that table. 
Test both triggers

result:
messages do not go as nuntium can't send messages if the phone number has a trailing '.0'

expected:
phone numbers should never be stored as float in an mbuilder table.

@mmuller can we automate a regression test please?

**Comment by bcardiff** [comment]
@nditada I was not able to repro this. I tried [this mbuilder app](https://gist.github.com/bcardiff/e3aa3ef3af262ec5fe7a) and get this behaviour


![screen shot 2015-09-02 at 12 28 48 pm](https://cloud.githubusercontent.com/assets/459923/9635831/a28d0cf4-516e-11e5-8e83-a424734db881.png)

something else you can add to find the bug?

**Comment by bcardiff** [comment]
I narrowed it to periodic tasks that try to send bulk sms:

sending a message to all at once does not work

![screen shot 2015-09-02 at 1 54 27 pm](https://cloud.githubusercontent.com/assets/459923/9638006/4dd18d0a-517a-11e5-9f53-4b6622f67138.png)

sending them one by one it does

![screen shot 2015-09-02 at 1 54 34 pm](https://cloud.githubusercontent.com/assets/459923/9638013/5fc28bea-517a-11e5-86d9-58e5c2a296e7.png)

recent activity

![screen shot 2015-09-02 at 1 54 54 pm](https://cloud.githubusercontent.com/assets/459923/9638018/67c8595a-517a-11e5-9292-ec03ff06a7be.png)

would this be consistent with your experiments @nditada ?
