### ISSUE TITLE
Replace Tire with elasticsearch gem.

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#58]
---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/58
- Originally Reported By: Mariano Coca
- Originally Created At: 2013-11-14 22:02:32+00:00

**Comment by nditada** [comment]
@bcardiff is this still valid or can we close it?

**Comment by bcardiff** [comment]
we can close it
