### ISSUE TITLE
New messages are not created inside selected if block

### ISSUE THREAD

**Issue by waj** [instedd/mbuilder#90]
Steps: create an "if", select it, press "new message".
Result: the message is created outside the "if" block.
Expected: the message gets created inside the "if" block.

---------------------------------------
- Imported from BitBucket: https://bitbucket.org/instedd/mbuilder/issue/90
- Originally Reported By: Nicolas di Tada
- Originally Created At: 2014-01-30 14:28:59+00:00

**Comment by bcardiff** [comment]
Currently there is an Add Step inside the if. So we don't require to select/click in the bottom add step button.
